DROP TABLE IF EXISTS clients;
CREATE TABLE IF NOT EXISTS clients
(
    id    SERIAL  PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    email VARCHAR(254) NOT NULL
);
DROP SEQUENCE IF EXISTS clients_id_seq;
CREATE SEQUENCE clients_id_seq START WITH 3 INCREMENT BY 1;